### ISSUE TITLE
part of your Math test data is being used for training ？

### ISSUE THREAD

**Issue by KarrXie** [QwenLM/ProcessBench#2]
your Math test data comes from Math, which include 5k queries. while curr published methods, including prm800k, only Math500 are being used to test, other 4.5k query are being used for train. that means part of your Math test data is being used for train, Is That right?

**Comment by chujiezheng** [comment]
![image](https://github.com/user-attachments/assets/456dd602-16ae-46ff-86c0-a5bec4479455)


No. We did the data contamination when fine-tuning Qwen2.5-Math-7B-Instruct on PRM800K.
