### ISSUE TITLE
unusually high F1 score

### ISSUE THREAD

**Issue by sunrise224** [QwenLM/ProcessBench#6]
I ran run_eval_prm_rlhflow.py and obtained an unusually high F1 score for Llama3.1-8B-PRM-Mistral-Data. In the correct file, I treated predictions of -1 as TP (True Positive) and the rest as FN (False Negative). In the error file, I treated predictions of -1 as FP (False Positive). Is this approach correct?

**Comment by chujiezheng** [comment]
Oh, we calculate F1 like:

```python
acc1 = np.mean([e['match'] for e in data1])
acc2 = np.mean([e['match'] for e in data2])
f1 = 2*acc1*acc2/(acc1+acc2)
```

**Comment by chujiezheng** [comment]
let me update more details of the metric calculation..

**Comment by sunrise224** [comment]
Thanks, this solved my problem. My reproduced results are basically consistent with those in the paper.
